info:
  type: test
  hash: 
  note: 
trainer:
  dataset: cifar10
  batch_size: 512
  lr: 0.05
  epochs: 50
  val_every: 2
  resume_from: 
  dry: False
  metrics1: val_acc
  metrics2: test_acc
cnn:
  dim: 16
  dim_mults: [1, 1, 1, 1]
  fc_dims: [10]
  full_attn: False
