info:
  type: test
  hash: 
  note: 
trainer:
  dataset: cifar10
  batch_size: 256
  lr: 0.01
  epochs: 200
  val_every: 1
  resume_from: 
  dry: False
  metrics1: val_acc
  metrics2: test_acc
  grad_acm: 1
  weight_decay: 0.001
cnn:
  dim: 64
  dim_mults: [1, 2, 4, 8]
  fc_dims: [1024, 128]
  full_attn: False
