info:
  type: test
  hash: 
  note: 
trainer:
  dataset: cifar10
  batch_size: 128
  lr: 0.01
  epochs: 100
  val_every: 1
  resume_from: 
  grad_acm: 1
  swa: 0.01
  weight_decay: 0.0005
  dry: False
  metrics1: val_acc
  metrics2: test_acc


